### PR TITLE
Add clippy to the standard docker build

### PR DESCRIPTION
**Pull request by jaynus**
This adds clippy to the standard building image to support amethyst/amethyst#1747

### CODE REVIEW

**Review by azriel91 — APPROVED** [review]
Yes please!

**Comment by azriel91** [comment]
We need @torkleyy, @fhaynes or @LucioFranco to publish the image after. That is, need to be added to the `amethystrs` org in docker hub, and have docker installed locally (I'm in the org, but haven't got docker)

**Review by torkleyy — APPROVED** [review]

**Comment by LucioFranco** [comment]
Has the image been published?

**Comment by torkleyy** [comment]
yep

**Pull request merged**
